export const SETUP_USER_BEGIN = "LOGIN_USER";
export const SETUP_USER_SUCCESS = "LOGIN_SUCCESS";
export const SETUP_USER_ERROR = "LOGIN_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_ERROR";

export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";
