export const SETUP_USER_BEGIN = "LOGIN_USER";
export const SETUP_USER_SUCCESS = "LOGIN_SUCCESS";
export const SETUP_USER_ERROR = "LOGIN_ERROR";

export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
